{% set prefix = "spacy-model-" %}
{% set lang = "it" %}
{% set name = lang + "_core_news" %}
{% set version = "3.2.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_sm-{{ version }}/{{ name }}_sm-{{ version }}.tar.gz
    sha256: a7f3ea3aff27273f55fb8fc6600c9864913b2aaca056c6a06a591cdd60972181

build:
  noarch: python
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
      commands:
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"

about:
  home: https://spacy.io
  license: CC BY-SA 4.0
  summary: Italian multi-task CNN trained on the Universal Dependencies and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/it

extra:
  recipe-maintainers:
    - JIVJGFJZKF
    - JennaLipscomb
    - mxr-conda
